### ISSUE TITLE
libFuzzer + random malloc failures

### ISSUE THREAD

**Issue by rockdaboot** [ralight/mallocfail#2]
Any idea how to combine mallocfail with libFuzzer ?

Background: I used __malloc_hook etc, but the libFuzzer seems to have it's own malloc hooks or implementation (well, at least it makes sense). So my fuzzer runs as usual. But later when I used the corpora (generated test data files) without libFuzzer, I get SIGSEGV (some code doesn't handle malloc failures gracefully). (Interestingly this is within dependency libraries (libunistring + iconv functionality).)

**Comment by ralight** [comment]
No, I don't but you might get better results with my valgrind fork which does the same thing, but better and with more control.

https://github.com/ralight/valgrind , fg-final branch. It's been a while since I looked at it so ping me if it doesn't work. I've just pushed what I think is the most recent version, but haven't checked it. Something that you might find useful is the ability to toggle on/off the malloc failures, either explicitly in code using the macros in the failgrind.h header, or by defining functions that will toggle the failures on/off when they enter/leave. It means you could do things like this, for example.

```
int main()
{
    setup_test_suite();
    run_test_suite();
}
```
Then:
`valgrind --tool=exp-failgrind --alloc-toggle=run_test_suite --alloc-fail-atstart=no ./test`

This gives `setup_test_suite()` a chance to run without any failures.

**Comment by rockdaboot** [comment]
Thanks for your answer :-)

I'll give it a try after FOSDEM.
